# Generated by Django 3.1.6 on 2021-02-05 01:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('voteapp', '0003_auto_20210205_0034'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rating',
            old_name='product',
            new_name='post',
        ),
    ]
