# Generated by Django 3.1.6 on 2021-02-05 02:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('voteapp', '0004_auto_20210205_0129'),
    ]

    operations = [
        migrations.CreateModel(
            name='WeeklyWinner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_no', models.IntegerField()),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='winners', to='voteapp.postcategory')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='winners', to='voteapp.weeklypost')),
            ],
        ),
    ]
