# Generated by Django 3.1.6 on 2021-02-22 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voteapp', '0006_auto_20210205_0224'),
    ]

    operations = [
        migrations.AddField(
            model_name='weeklypost',
            name='week_number',
            field=models.IntegerField(default=1),
        ),
    ]
